Task 9.2
BartekOgien/Bartosz-Ogieniewski-kodilla-java pull request #12
Opened 2017-09-28 18:47 UTC by BartekOgien

Please check

2017-09-28 19:51 UTC, MARudnicki requested changes
Dodaj pakiety
challenge1
challenge2
W challenge2 w roocie niech bedzie tylko klasa z main, i kolejne pakiety np. orders, products itd

2017-09-28 19:51 UTC, MARudnicki commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/ShoppingProcessor.java
> +        if(isBought) {
do product i dataOfOrder odwoluj sie przez gettery

2017-09-28 19:51 UTC, MARudnicki commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/ShoppingProcessor.java
> +            return new ShoppingDTO(shopRequest.getUser(), true);
jak wyzej

2017-09-28 19:51 UTC, MARudnicki commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/User.java
> +
zla kolejnosc w klasie: zmienne, konstruktory, metody. (abstract, public, protected, private)

2017-09-28 19:51 UTC, MARudnicki commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/ShoppingDTO.java
> +    }
zla kolejnosc w klasie: zmienne, konstruktory, metody. (abstract, public, protected, private)

2017-09-29 18:30 UTC, BartekOgien commented
Poprawione

2017-10-06 17:01 UTC, merged