Task 9.4
BartekOgien/Bartosz-Ogieniewski-kodilla-java pull request #13
Opened 2017-09-29 19:03 UTC by BartekOgien

Check please

2017-09-29 19:58 UTC, MARudnicki requested changes

2017-09-29 19:58 UTC, MARudnicki commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/challenge3/suppliers/ExtraFoodShop.java
> +    private final String name = "Extra Food Shop";
stale przyjelo sie zgodnie z konwencja zapisywac jako 'private final static' oraz z nazwa uppercase - NAME

2017-09-29 19:58 UTC, MARudnicki commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/challenge3/suppliers/ExtraFoodShop.java
> +    private final String name = "Extra Food Shop";
czyli powinno byc private final static NAME = "Extra..."

2017-09-29 19:58 UTC, MARudnicki commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/challenge3/suppliers/ExtraFoodShop.java
> +    private final String name = "Extra Food Shop";
https://stackoverflow.com/questions/1415955/private-final-static-attribute-vs-private-final-attribute

2017-09-29 19:58 UTC, MARudnicki commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/challenge3/orders/OrderRepository.java
> +    }
sformatuj date, tak aby byla bardziej user-friendly
 order.getDateOfOrder()
np.
https://www.mkyong.com/java8/java-8-how-to-format-localdatetime/

2017-09-29 19:58 UTC, MARudnicki commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/challenge3/suppliers/GlutenFreeShop.java
> +    private final String name = "Gluten Free Shop";
jak wyzej

2017-09-29 19:58 UTC, MARudnicki commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/challenge3/suppliers/HealthyShop.java
> +    private final String name = "Healthy Shop";
jak wyzej

2017-09-30 18:04 UTC, BartekOgien commented
Poprawione

2017-10-06 17:01 UTC, merged