Task 9.5
BartekOgien/Bartosz-Ogieniewski-kodilla-java pull request #14
Opened 2017-10-01 09:24 UTC by BartekOgien

Sprawdź i czekam na uwagi

2017-10-01 20:08 UTC, MARudnicki requested changes

2017-10-01 20:08 UTC, MARudnicki commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/challenge4/Application.java
> +
Zamiast przekazywac zawsze flightRepository.getFlightList() do Engine'ow, stworz w FlightSearchEngine i FlightSearchEngineAdvances zmienna globalna FlightRepository

2017-10-01 20:08 UTC, MARudnicki commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/challenge4/Flights/FlightSearchEngineAdvanced.java
> +}
Czy masz pomysl jak to rozwiazac, jesli beda 3 przesiadki ?

2017-10-01 20:08 UTC, MARudnicki commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/challenge4/Users/UserRequest.java
> +
pola private

2017-10-01 20:08 UTC, MARudnicki commented on kodilla-good-patterns/src/main/java/com/kodilla/good/patterns/challenges/challenge4/Flights/FlightService.java
> +    public void userInformation(UserRequest userRequest) {
metody powinny byc czasowanikami

2017-10-02 17:17 UTC, BartekOgien commented
Poprawiłem to na co zwróciłeś mi uwagę oprócz sytuacji z kilkoma przesiadkami

2017-10-06 17:01 UTC, merged