Task 7.3
BartekOgien/Bartosz-Ogieniewski-kodilla-java pull request #2
Opened 2017-09-13 17:16 UTC by BartekOgien

Testowa wiadomosc

2017-09-13 17:17 UTC, MARudnicki requested changes
wiadomosc testowa

2017-09-13 17:17 UTC, MARudnicki commented on kodilla-stream/src/main/java/com/kodilla/stream/immutable/Book.java
> +
nie zostawiaj tylu miejsca - code style

2017-09-14 16:26 UTC, BartekOgien commented
Check please that task

2017-09-14 18:07 UTC, MARudnicki requested changes

2017-09-14 18:07 UTC, MARudnicki commented on kodilla-stream/src/main/java/com/kodilla/stream/StreamMain.java
> +                                                                      .filter(f -> f.getNumberOfPosts()>0)
"odfiltruje tylko tych użytkowników, którzy mają co najmniej 20 lat"
- twoj program przestanie dzialac prawidlowo w 2018. To jest do poprawy

2017-09-16 11:33 UTC, MARudnicki commented on kodilla-stream/src/main/java/com/kodilla/stream/StreamMain.java
> +                                                                      .filter(f -> f.getNumberOfPosts()>0)
Program przestanie dzialac w 2018. Warunek jest do poprawy

2017-09-20 17:54 UTC, merged