Task 11.2
BartekOgien/Bartosz-Ogieniewski-kodilla-java pull request #20
Opened 2017-10-12 18:04 UTC by BartekOgien

Please check

2017-10-12 18:38 UTC, MARudnicki requested changes

2017-10-12 18:38 UTC, MARudnicki commented on kodilla-patterns/src/main/java/com/kodilla/patterns/prototype/library/Library.java
> +    String name;
private String name

2017-10-12 18:38 UTC, MARudnicki commented on kodilla-patterns/src/main/java/com/kodilla/patterns/prototype/library/Library.java
> +    Set<Book> books = new HashSet<>();
private Set ...

2017-10-12 18:38 UTC, MARudnicki commented on kodilla-patterns/src/main/java/com/kodilla/patterns/prototype/library/Library.java
> +        for(Book theSet : books) {
Book theSet ???
Book book : books

2017-10-12 18:38 UTC, MARudnicki commented on kodilla-patterns/src/main/java/com/kodilla/patterns/prototype/library/Library.java
> +        }
Zamiast
        for(Book theSet : books) {
            clonedLibrary.books.add(theSet);
        }
Mozna zapisac ktorej
clonedLibrary.books.addAll(books);

2017-10-13 17:06 UTC, BartekOgien commented
Poprawione

2017-10-18 17:12 UTC, merged