Task 7.4 completed
BartekOgien/Bartosz-Ogieniewski-kodilla-java pull request #4
Opened 2017-09-14 17:24 UTC by BartekOgien

PLease check task

2017-09-14 18:17 UTC, MARudnicki requested changes

2017-09-14 18:17 UTC, MARudnicki commented on kodilla-stream/src/main/java/com/kodilla/stream/world/Country.java
> +    private final BigDecimal peopleQuantity;
nameOfCountry - do tej zmiennej nie mozna sie odwolac. Dodaj getter lub wyrzuc ja

2017-09-14 18:17 UTC, MARudnicki commented on kodilla-stream/src/main/java/com/kodilla/stream/world/Continent.java
> +    private final List<Country> countryList = new ArrayList<>();
continentName - do tej zmiennej nie mozna sie odwolac. Dodaj getter lub wyrzuc ja

2017-09-15 17:41 UTC, BartekOgien commented
Napisałem złą nazwę commita miało być Task 7.4 corrected getters added

2017-09-20 17:54 UTC, merged